[package]
name = "common"
version = "0.1.0"
authors = ["Daniel Graczer <daniel@fleek.co>"]
edition = "2018"

[dependencies]
crc32fast = "1.3.2"
ic-kit = "0.4.4"
ic-cdk = "0.5.1"
ic-types = "0.3.0"
hex = {version = "0.4.3", features = ["serde"] }
serde = { version="1.0.137", features = ["derive"] }
sha2 = "0.10.2"
